language: node_js
node_js:
  - '10'
  - '9'
  - '8'
install:
  - npm install
  - npm install -g codecov
script:
  - npm run build
  - npm t

jobs:
  include:
    - state: npm release
      if: tag IS present
      node_js: '10'
      script: npm run build
      deploy:
        provider: npm
        email: '$NPM_EMAIL'
        api_key: '$API_TOKEN'
        skip_cleanup: true
        on:
          tags: true
